spring:
  application:
    name: EurekaPeers
management:
  endpoints:
    web:
      exposure:
        include: prometheus
eureka:
  instance:
    metadataMap:
      "prometheus.path": "/actuator/prometheus"
---
spring:
  config:
    activate:
      on-profile: peer1
eureka:
  instance:
    hostname: Daweis-MBP.fios-router.home #watch out this
    prefer-ip-address: false
    appname: eureka
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/ # watch out the host name should be same with peer2
server:
  port: 8761
---
spring:
  config:
    activate:
      on-profile: peer2
eureka:
  instance:
    hostname: localhost #watch out this
    prefer-ip-address: false
    appname: eureka
  client:
    serviceUrl:
      defaultZone: http://Daweis-MBP.fios-router.home:8761/eureka/ # watch out the host name should be same with peer1
server:
  port: 8762
